export type ImportDataTableData = {
	transactionId: string;
	accountGroupingId: string;
	date: string;
	description: string;
	amount: number;
	linked?: boolean;
	reconciled?: boolean;
	dataChecked?: boolean;
	accountTitle: string;
	accountId: string;
	complete?: boolean;
	categoryId?: string;
	categoryTitle?: string;
	billId?: string;
	billTitle?: string;
	budgetId?: string;
	budgetTitle?: string;
	tagId?: string;
	tagTitle?: string;
};
